# https://taskfile.dev

version: '3'

vars:
  BIN:
    sh: basename $PWD

tasks:
  default: [{task: build}]

  build:
    sources:
      - main.go
    generates:
      - "{{.BIN}}"
    cmds:
      - go build -ldflags '-s -w' -o {{.BIN}}
      - command -v upx >/dev/null && upx {{.BIN}} || echo upx not found, skipping
    env:
      CGO_ENABLED: 0

  clean: rm -f {{.BIN}}

  test:hey:
    cmds:
      - go tool hey -c 10 -n 1000 -m POST http://localhost:9999/
      - go tool hey -c 10 -n 10000 -m GET http://localhost:9999/

  test:cassowary:
      - go tool cassowary run -c 10 -n 1000 -u http://localhost:9999/ --postfile <(echo test)
      - go tool cassowary run -c 10 -n 10000 -u http://localhost:9999/
