# https://taskfile.dev

version: '3'

vars:
  BIN:
    sh: basename $PWD

tasks:
  default: [{task: build}]

  build:
    sources:
      - main.go
    generates:
      - "{{.BIN}}"
    cmds:
      - go build -o {{.BIN}}
    env:
      CGO_ENABLED: 0

  clean: rm -f {{.BIN}}

  test:hey: go tool hey -c 1 -n 100 http://localhost:9999/
  test:cassowary: go tool cassowary run -c 1 -n 100 -u http://localhost:9999/
