pre-commit:
  commands:
    gofumpt:
      run: go tool gofumpt -w {staged_files}
      glob: "*.go"
      stage_fixed: true

    lint:
      run: go tool golangci-lint run

    govulncheck:
      run: go tool govulncheck

    editorconfig-checker:
      run: go tool editorconfig-checker
