# https://taskfile.dev

version: '3'

vars:
  GOCMD_TEST: go run gotest.tools/gotestsum@v1.12.0 -- ./...
  FLAG_NOCACHE: -count 1
  FLAG_INTEGRATION: -tags integration

tasks:
  default:
    - task: test:unit

  test:
    - task: test:unit

  test:unit: '{{ .GOCMD_TEST }}'
  test:unit-nocache: '{{ .GOCMD_TEST }} {{ .FLAG_NOCACHE }}'
  test:integration: '{{ .GOCMD_TEST }} {{ .FLAG_INTEGRATION }}'
  test:integration-nocache: '{{ .GOCMD_TEST }} {{ .FLAG_INTEGRATION }} {{ .FLAG_NOCACHE }}'

  install: go install ./cmd/...

  update-deps:
    - go get -u ./...
    - go mod tidy

  docs: go run golang.org/x/pkgsite/cmd/pkgsite@latest
