# https://taskfile.dev

version: '3'

setopt: [globstar]

vars:
  COVERPROFILE: c.out

  GOCMD_TEST: go tool gotestsum ./...
  GOCMD_TEST_INTEGRATION: '{{.GOCMD_TEST}} -tags integration'
  GOCMD_TEST_NOCACHE: '{{.GOCMD_TEST}} -count 1'
  GOCMD_TEST_INTEGRATION_NOCACHE: '{{.GOCMD_TEST}} -tags integration -count 1'

tasks:
  default:
    - task: test:unit
    - task: vuln
    - task: lint

  test:
    - task: test:unit

  test:unit: '{{ .GOCMD_TEST }}'
  test:unit-nocache: '{{ .GOCMD_TEST_NOCACHE }}'
  test:integration: '{{ .GOCMD_TEST_INTEGRATION }}'
  test:integration-nocache: '{{ .GOCMD_TEST_INTEGRATION_NOCACHE }}'

  test:coverprofile:
    sources:
      - '**/*.go'
    generates:
      - '{{.COVERPROFILE}}'
    cmds:
      - go test ./... -coverprofile {{.COVERPROFILE}}

  test:uncover:
    deps:
      - test:coverprofile
    cmds:
      - go tool uncover {{.COVERPROFILE}}

  lint: go tool golangci-lint run
  lint:editorconfig: go tool editorconfig-check
  vuln: go tool govulncheck ./...

  build: go tool goreleaser build --auto-snapshot --clean

  install: go install ./cmd/...

  update-deps:
    - go get -u ./...
    - go mod tidy

  docs: go tool pkgsite

  clean: rm -f {{.COVERPROFILE}}
