# https://taskfile.dev

version: '3'

vars:
  GOCMD_TEST: go test ./... -cover
  FLAG_NOCACHE: -count 1
  FLAG_INTEGRATION: -tags integration
  OUTDIR: ./out

tasks:
  default:
    cmds:
      - task: test:unit

  test:unit:
    cmds:
      - '{{ .GOCMD_TEST }}'

  test:unit-nocache:
    cmds:
      - '{{ .GOCMD_TEST }} {{ .FLAG_NOCACHE }}'

  test:integration:
    cmds:
      - '{{ .GOCMD_TEST }} {{ .FLAG_INTEGRATION }}'

  test:integration-nocache:
    cmds:
      - '{{ .GOCMD_TEST }} {{ .FLAG_INTEGRATION }} {{ .FLAG_NOCACHE }}'

  install: go install ./cmd/...

  clean:
    cmds:
      - rm -rf {{ .OUTDIR }}
