services:
  nats1:
    image: synadia/nats-server:v2.11.0-preview.1-alpine3.19
    entrypoint:
      - nats-server
      - -js
      - --routes=nats-route://ruser:T0pS3cr3t@nats2:6222
      - --routes=nats-route://ruser:T0pS3cr3t@nats3:6222
    depends_on:
      - nats2
      - nats3
  nats2:
    image: synadia/nats-server:v2.11.0-preview.1-alpine3.19
    entrypoint:
      - nats-server
      - -js
  nats3:
    image: synadia/nats-server:v2.11.0-preview.1-alpine3.19
    entrypoint:
      - nats-server
      - -js
  box:
    image: natsio/nats-box:0.14.3
    command: sleep infinity
    working_dir: /work
    volumes:
      - ./backup:/work/backup:ro
    environment:
      NATS_URL: nats://nats:4222/
  benthos:
    image: jeffail/benthos:4
    working_dir: /work
    environment:
      NATS_URL: nats://nats1:4222/
    volumes:
      - ./seed.yaml:/benthos.yaml:ro
