services:

  nats1:
    image: synadia/nats-server:v2.11.0-preview.1-alpine3.19
    ports:
      - 4222:4222
      - 8222:8222
    depends_on:
      - nats2
      - nats3
    entrypoint:
      - nats-server
      - -js
      - "--routes=nats-route://ruser:T0pS3cr3t@nats2:6222"
      - "--routes=nats-route://ruser:T0pS3cr3t@nats3:6222"

  nats2:
    image: synadia/nats-server:v2.11.0-preview.1-alpine3.19
    ports:
      - 4223:4222
      - 8223:8222
    entrypoint: ["nats-server", "-js"]

  nats3:
    image: synadia/nats-server:v2.11.0-preview.1-alpine3.19
    ports:
      - 4224:4222
      - 8224:8222
    entrypoint: ["nats-server", "-js"]

  client:
    image: natsio/nats-box:0.14.2
    command: sleep infinity
    working_dir: /work
    volumes:
      - ./backup:/work/backup:ro
    environment:
      NATS_URL: nats://nats:4222/

  benthos:
    image: jeffail/benthos:4
    working_dir: /work
    volumes:
      - ./seed.yaml:/work/seed.yaml:ro
